services:
  api:
    build: .
    container_name: tuplana_api
    restart: unless-stopped
    ports:
      - "3257:3000"
    env_file:
      - .env
    volumes:
      - whatsapp_sessions:/sessions

volumes:
  whatsapp_sessions:
